// Generated by CoffeeScript 1.10.0
(function() {
  Router.configure({
    layoutTemplate: 'MasterLayout',
    loadingTemplate: 'Loading',
    notFoundTemplate: 'NotFound'
  });

  Router.route('/', {
    name: 'home',
    controller: 'HomeController',
    where: 'client'
  });

}).call(this);

//# sourceMappingURL=routes.js.map
