// Generated by CoffeeScript 1.10.0
(function() {
  Template.Home.events({});

  Template.Home.helpers({});

  Template.Home.onCreated(function() {});

  Template.Home.onRendered(function() {});

  Template.Home.onDestroyed(function() {});

}).call(this);

//# sourceMappingURL=home.js.map
