// Generated by CoffeeScript 1.10.0
(function() {
  this.HomeController = RouteController.extend({
    subscriptions: function() {},
    waitOn: function() {},
    data: function() {},
    onRun: function() {
      return this.next();
    },
    onRerun: function() {
      return this.next();
    },
    onBeforeAction: function() {
      return this.next();
    },
    action: function() {
      return this.render();
    },
    onAfterAction: function() {},
    onStop: function() {}
  });

}).call(this);

//# sourceMappingURL=home_controller.js.map
